<?php

namespace App\Models;

use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Uuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Kirschbaum\PowerJoins\PowerJoins;
use Ramsey\Uuid\Uuid as RamseyUuid;
use Staudenmeir\EloquentHasManyDeep\HasRelationships;

class GuestSession extends Model
{
    use HasFactory, PowerJoins, HasRelationships;

    protected $fillable = [
        'guest_id',
        'user_agent',
        'device',
        'device_type',
        'browser',
        'platform',
        'platform_version',
        'desktop',
        'languages',
        'is_robot',
        'robot_name',
        'first_seen',
        'mobile',
        'phone',
        'tablet',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (self $model): void {
           $model->guest_id = RamseyUuid::uuid4()->toString();
        });
    }
    
    public function guest(): BelongsTo
    {
        return $this->belongsTo(Guest::class);
    }

    public function recordings(): HasMany
    {
        return $this->hasMany(Recording::class);
    }
}
